#7 Apache 软件基金会商标指南 翻译初稿
alc-beijing/translation pull request #14
Opened 2020-10-31 13:52 UTC by taskmgr

在提交的翻译文件的末尾我总结了下我觉得有问题的地方，请查看~

2020-11-01 09:21 UTC, WillemJiang commented on ASF/policy/marks/Apache 软件基金会商标使用指南.md
> +# 如何使用 Apache 项目徽标
如果说logo的话，大部分人都应该能够明白。
所以我不太建议把logo翻译。

2020-11-01 12:10 UTC, WillemJiang approved these changes

2020-11-02 08:16 UTC, lijiangsheng1 requested changes
Brand 更换为“品牌”，其它没有什么问题。

2020-11-03 06:45 UTC, WillemJiang approved these changes

2020-11-03 06:45 UTC, merged