Update newcommitter.md
alc-beijing/translation pull request #88
Opened 2023-02-28 02:37 UTC by L-Y-L

* [相关链接（建议）]：Issue #87 
* [描述信息（可选）]：
* [备注说明（可选）]：

2023-02-28 03:40 UTC, ShawnJim commented on apache/community/newcommitter.md
> +我们如何评价？
`How do we evaluate?` 翻译成 `我们如何评估?` 会不会好一点

2023-02-28 03:51 UTC, ShawnJim commented on apache/community/newcommitter.md
> +-   通过他们如何回应批评。
这里翻译成 `通过他们对批评的回应` 会不会更好一点点。

2023-02-28 04:06 UTC, ShawnJim commented on apache/community/newcommitter.md
> +-   通过他们如何参与群体决策过程。
这里翻译为
``` txt
- 通过他们参与群体决策的方式

or 

- 通过他们如何参与群体决策
```
会不会好一点~

2023-02-28 04:07 UTC, ShawnJim commented on apache/community/newcommitter.md
> +-   通过他们如何参与群体决策过程。
这里翻译为

- 通过他们参与群体决策的方式

or 

- 通过他们如何参与群体决策
会不会好一点~

2023-02-28 04:09 UTC, ShawnJim commented on apache/community/newcommitter.md
> +-   通过他们如何参与群体决策过程。
```
- 通过他们如何参与群体决策过程。
```
这里翻译为
```txt
- 通过他们参与群体决策的方式

or 

- 通过他们如何参与群体决策
```
会不会好一点~

2023-02-28 05:50 UTC, 6freeair2016 commented on apache/community/newcommitter.md
> +识别潜在的新提交者，发起投票承认他们是提交者并处理相关文件是整个社区可以贡献的任务。
发现有潜力的新提交者，发起提名他们为提交者的投票并且处理与此相关的文档，是整个社区成员可以致力的任务。

2023-02-28 06:59 UTC, tuohai666 requested changes

2023-02-28 06:59 UTC, tuohai666 commented on apache/community/newcommitter.md
> +## 评估新候选人承诺的指南
评估新候选人是否适合成为提交者的指南

2023-02-28 07:15 UTC, tuohai666 requested changes

2023-02-28 07:15 UTC, tuohai666 commented on apache/community/newcommitter.md
> +以下是在评估候选人的承诺资格时需要考虑的一些要点。
提交者资格

2023-02-28 07:15 UTC, tuohai666 commented on apache/community/newcommitter.md
> +我们如何评价？
评价建议统一改为评估

2023-02-28 07:15 UTC, tuohai666 commented on apache/community/newcommitter.md
> +### 提交
翻成投入或奉献比较好

2023-03-01 01:43 UTC, L-Y-L commented on apache/community/newcommitter.md
> +我们如何评价？
ok

2023-03-01 01:43 UTC, L-Y-L commented on apache/community/newcommitter.md
> +我们如何评价？
ok

2023-03-01 01:47 UTC, L-Y-L commented on apache/community/newcommitter.md
> +## 评估新候选人承诺的指南
ok

2023-03-01 01:47 UTC, L-Y-L commented on apache/community/newcommitter.md
> +以下是在评估候选人的承诺资格时需要考虑的一些要点。
ok

2023-03-01 01:49 UTC, L-Y-L commented on apache/community/newcommitter.md
> +### 提交
ok

2023-03-01 01:51 UTC, L-Y-L commented on apache/community/newcommitter.md
> +-   通过他们如何参与群体决策过程。
好的

2023-03-01 02:31 UTC, 6freeair2016 requested changes

2023-03-02 04:43 UTC, L-Y-L commented on apache/community/newcommitter.md
> +提议前不要等太久，也不要操之过急。有一个权衡和及时性的问题。到了很明显我们应该邀请他们的地步。这会鼓励他们并让他们保持热情。如果我们放置得太久，那么我们就有可能让他们失望。
提议不要拖太久，也不能过于匆忙，需要考虑时效性的问题。时机来临，很显然我们应该邀请他们，这会鼓舞他们，令之保持热情。如果我们拖得太久，就有可能让他们感到失望。

2023-03-02 04:52 UTC, L-Y-L commented on apache/community/newcommitter.md
> +-   他们是否有助于回答邮件列表中提出的问题？他们是否表现出乐于助人的态度并尊重他人的想法？
谢谢

2023-03-02 04:53 UTC, L-Y-L commented on apache/community/newcommitter.md
> +-   通过他们通过电子邮件进行的互动。
Thank you.

2023-03-02 06:18 UTC, L-Y-L reviewed
ok

2023-03-06 01:46 UTC, L-Y-L reviewed
ok

2023-04-04 12:13 UTC, merged

2023-04-04 12:13 UTC, WillemJiang commented
Thanks the contribution of  @L-Y-L and the review work of @tuohai666, @ShawnJim, @6freeair2016, @willemjiang