issues 89 完成翻译
alc-beijing/translation pull request #93
Opened 2023-10-23 07:01 UTC by wjsvec

* [相关链接（建议）]：[Issue #89](https://github.com/alc-beijing/translation/issues/89)
* [描述信息（可选）]：成 Apache Security 2022 年度报告，翻译工作
* [备注说明（可选）]：

2023-10-26 11:36 UTC, WillemJiang requested changes

2023-10-26 11:36 UTC, WillemJiang commented on apache/securityreport/Apache软件安全报告2022.md
> +**Apache 软件基金会** （ASF） 的安全委员会负责监督和协调 350 多个 Apache 项目中的漏洞处理，每天处理 60 多封传入电子邮件。成立于 2002 年，我们对于如何处理问题有一个[一致流程](https://s.apache.org/cveprocess)，这个流程包括我们的项目必须如何披露安全问题。2022 年期间，ASF 聘请了一名管理员来帮助处理即将到来的漏洞处理工
“每天处理 60 多封传入电子邮件传入电子邮件” 建议翻译为 “每天要处理收到的60多封电子邮件”。 
“一名管理员来帮助处理即将到来的漏洞处理工作” 建议翻译为 ““一名管理员来帮助处理接收到的漏洞响应工作”

2023-10-26 11:36 UTC, WillemJiang commented on apache/securityreport/Apache软件安全报告2022.md
> +在任何 ASF 项目中发现安全问题的任何人都可以将其报告给 [security@apache.org](mailto:security@apache.org)，这些问题将被记录下来并传递给相关的[专门安全团队](https://apache.org/security/projects.html)或私人**项目管理委员会** （project management committees PMC）
传递 改成 转发，“ 私人**项目管理委员会** 进行处理” 改成 “**项目管理委员会**在私下里进行处理”

2023-10-26 15:09 UTC, wjsvec commented on apache/securityreport/Apache软件安全报告2022.md
> +**Apache 软件基金会** （ASF） 的安全委员会负责监督和协调 350 多个 Apache 项目中的漏洞处理，每天处理 60 多封传入电子邮件。成立于 2002 年，我们对于如何处理问题有一个[一致流程](https://s.apache.org/cveprocess)，这个流程包括我们的项目必须如何披露安全问题。2022 年期间，ASF 聘请了一名管理员来帮助处理即将到来的漏洞处理工
已修改🥳

2023-10-26 15:09 UTC, wjsvec commented on apache/securityreport/Apache软件安全报告2022.md
> +在任何 ASF 项目中发现安全问题的任何人都可以将其报告给 [security@apache.org](mailto:security@apache.org)，这些问题将被记录下来并传递给相关的[专门安全团队](https://apache.org/security/projects.html)或私人**项目管理委员会** （project management committees PMC）
已修改🥳

2023-10-26 15:09 UTC, wjsvec commented
已经根据建议修改

2023-10-31 00:47 UTC, WillemJiang commented
Merge the translation into the main branch with thanks to Jiashu.

2023-10-31 00:47 UTC, merged